name: Python CI

# Trigger the workflow on push to the 'main' branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Use windows-latest for Windows-based runners
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks out the code from your repository

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run Python script
      run: python py.py  # Replace 'your_script.py' with the name of your Python script
